services:
  postgres: # 실행할 서비스 정의: 이미지 이름과 관계없이 우리가 짓는 거임
    image: postgres:15
    restart: always # 실행을 할 때마다 항상 재시작을 해라
    # 도커 이미지 안에서 실행됐던, 생성됐던 파일들은 도커 이미지 안에서만 존재한다, 도커를 종료하면 다 날아갈 수 있기 때문에
    # host os의 볼륨과 매핑을 해준다, 이미지가 꺼지거나 삭제가 되도 postgresql안에 있는 데이터를 유지 할 수 있다.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # 상대 경로는 컴포즈파일 기준 | 왼쪽(host os의 위치):오른쪽(이미지 안에 존재하는 위치)
    ports: # host os 의 포트와 이미지의 포트 매핑 | 왼쪽(host os의 포트):오른쪽(이미지 포트)
      - "5432:5432"
    environment: # 데이터베이스에 대한 정보를 추가로 넣어 줄 수 있다.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # default database

